replicaCount: 1

image:
  repository: ddocker122/tractor-xapp-orchestrator
  tag: latest
  pullPolicy: IfNotPresent

env:
  NORMALIZER_URL: http://tractor-normalizer:5002
  BUFFER_URL: http://tractor-buffer:5005
  MODEL_URL: http://tractor-model:5003
  MODEL_TYPE: CNN
  NCLASS: "4"
  ALL_FEATS: "31"
  STREAM_ID: default
  MODEL_PATH: /mnt/model/model.pt
  NORM_PATH: /mnt/model/norm.pkl

ports:
  - name: http
    containerPort: 4200

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
