replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: ddocker122/tractor-xapp-model
  tag: latest

service:
  port: 5003

serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ''

volumeMounts:
  model:
    hostPath: 
      /home/lapdk/workspace/oai-v210/tractor/src/xapp/models/model.32.cnn.pt
    mountPath: /mnt/model/model.pt
resources: {}
nodeSelector: []
tolerations: []
affinity: {}
