replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: ddocker122/tractor-xapp-model
  tag: latest

service:
  port: 5003

serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ''

volumeMounts:
  model:
    mountPath: /mnt/model/model.pt

persistentVolume:
  enabled: true
  name: tractor-model-pv
  claimName: tractor-model-pvc
  size: 1Gi
  accessMode: ReadWriteMany
  hostPath: /home/lapdk/workspace/oai-v210/tractor/src/xapp/models

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
