# -*- coding: utf-8 -*-
"""baselines.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f1yFkBxKmDRPD58LZwFu_TeWpKfsWqmR
"""

!pip install -q torch-geometric

import os, math, warnings
import joblib
from dataclasses import dataclass
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.nn import SAGEConv
from sklearn.preprocessing import RobustScaler
from sklearn.metrics import f1_score
import matplotlib.pyplot as plt
from collections import deque
import random
import seaborn as sns
from torch_geometric.nn import GCNConv  # for GCN baseline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
try:
    import xgboost as xgb
    XGB_AVAILABLE = True
except Exception:
    XGB_AVAILABLE = False
warnings.filterwarnings('ignore')
os.makedirs('plots', exist_ok=True)


def set_seeds(seed=42):
    random.seed(seed);
    np.random.seed(seed);
    torch.manual_seed(seed)


device = torch.device('cpu')

@dataclass
class Config:
    train_file: str = 'train.csv'
    test_file: str = 'test.csv'
    window_size: int = 10
    gs_epochs: int = 120
    ddqn_episodes: int = 1500
    sim_steps: int = 15
    n_seeds: int = 3
    ma_window: int = 50
    plots_dir: str = 'plots'


cfg = Config()


class FocalLoss(nn.Module):
    def __init__(self, alpha=1, gamma=2):
        super().__init__()
        self.alpha = alpha
        self.gamma = gamma

    def forward(self, inputs, targets):
        ce_loss = F.cross_entropy(inputs, targets, reduction='none')
        pt = torch.exp(-ce_loss)
        focal_loss = self.alpha * (1 - pt) ** self.gamma * ce_loss
        return focal_loss.mean()


class LabelingxApp(nn.Module):
    def __init__(self, in_dim: int, hidden_dim: int = 64):
        super().__init__()
        self.conv1 = SAGEConv(in_dim, hidden_dim)
        self.conv2 = SAGEConv(hidden_dim, hidden_dim)
        self.conv3 = SAGEConv(hidden_dim, hidden_dim // 2)
        self.bn1 = nn.BatchNorm1d(hidden_dim)
        self.bn2 = nn.BatchNorm1d(hidden_dim)
        self.bn3 = nn.BatchNorm1d(hidden_dim // 2)
        self.dropout = nn.Dropout(0.2)
        self.load_head = nn.Sequential(nn.Linear(hidden_dim // 2, 32), nn.ReLU(), nn.Linear(32, 3))
        self.embeddings = None

    def forward(self, x, edge_index):
        h = F.relu(self.bn1(self.conv1(x, edge_index)))
        h = F.relu(self.bn2(self.conv2(h, edge_index)))
        h = F.relu(self.bn3(self.conv3(h, edge_index)))
        h = self.dropout(h)
        self.embeddings = h.detach()
        return self.load_head(h)

# -------------------
# Additional Labeling Models
# -------------------
class GCNLabelingxApp(nn.Module):
    def __init__(self, in_dim: int, hidden_dim: int = 64):
        super().__init__()
        self.conv1 = GCNConv(in_dim, hidden_dim)
        self.conv2 = GCNConv(hidden_dim, hidden_dim)
        self.conv3 = GCNConv(hidden_dim, hidden_dim // 2)
        self.bn1 = nn.BatchNorm1d(hidden_dim)
        self.bn2 = nn.BatchNorm1d(hidden_dim)
        self.bn3 = nn.BatchNorm1d(hidden_dim // 2)
        self.dropout = nn.Dropout(0.2)
        self.load_head = nn.Sequential(nn.Linear(hidden_dim // 2, 32), nn.ReLU(), nn.Linear(32, 3))

    def forward(self, x, edge_index):
        h = F.relu(self.bn1(self.conv1(x, edge_index)))
        h = F.relu(self.bn2(self.conv2(h, edge_index)))
        h = F.relu(self.bn3(self.conv3(h, edge_index)))
        h = self.dropout(h)
        return self.load_head(h)


def train_graph_labeler(train_graphs: list, test_graphs: list, model: nn.Module, cfg: Config, seed: int, lr=0.01, every=20, tag="GCN"):
    set_seeds(seed)
    model = model.to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=lr)
    best_f1 = 0.0
    best_acc = 0.0
    best_path = None

    for epoch in range(cfg.gs_epochs):
        model.train()
        loss_total = 0.0
        for g in train_graphs:
            prb = g.prb
            y = np.digitize(prb, np.percentile(prb, [33, 66]))
            y_t = torch.LongTensor(y).to(device)

            opt.zero_grad()
            logits = model(g.x.to(device), g.edge_index.to(device))
            loss = F.cross_entropy(logits, y_t)
            loss.backward()
            opt.step()
            loss_total += loss.item()

        if epoch % every == 0:
            model.eval()
            all_true, all_pred = [], []
            with torch.no_grad():
                for g in test_graphs:
                    prb = g.prb
                    y_true = np.digitize(prb, np.percentile(prb, [33, 66]))
                    pred = model(g.x.to(device), g.edge_index.to(device)).argmax(1).cpu().numpy()
                    all_true.extend(y_true)
                    all_pred.extend(pred)

            macro_f1 = f1_score(all_true, all_pred, average='macro')
            acc = (np.array(all_true) == np.array(all_pred)).mean()
            print(f"[Seed {seed}] {tag} E{epoch}: Loss={loss_total / max(1,len(train_graphs)):.3f}, Acc={acc:.0%}, Macro-F1={macro_f1:.3f}")

            if macro_f1 > best_f1:
                best_f1 = macro_f1
                best_acc = acc
                best_path = f'{tag.lower()}_labeling_acc{int(best_acc*100)}_f1{int(best_f1*100)}_seed{seed}.pth'
                torch.save(model.state_dict(), best_path)

    model.load_state_dict(torch.load(best_path))
    print(f"[Seed {seed}] {tag} Labeling best Macro-F1: {best_f1:.0%} | Acc: {best_acc:.0%} | saved: {best_path}")
    return model

class ORANSimulator:
    def __init__(self, use_neighbor_interference=True, use_prb_overload_penalty=True):
        self.use_neighbor_interference = use_neighbor_interference
        self.use_prb_overload_penalty = use_prb_overload_penalty

    def step(self, actions: list, current_state: dict, num_ues: int) -> tuple:
        alloc_map = {0: 0.2, 1: 0.5, 2: 0.8}
        allocs = np.array([alloc_map[a] for a in actions])
        requested_allocs = allocs.copy()  # Track for PRB violation

        over_request = max(0.0, requested_allocs.sum() - 1.0)
        over_per_ue = over_request / max(1, num_ues)

        prb_violation = max(0, np.sum(requested_allocs) - 1.0) * 100
        if allocs.sum() > 1.0:
            allocs *= 1.0 / allocs.sum()

        curr_prb = np.array(current_state['prb'])
        curr_tput = np.array(current_state['tput'])
        curr_delay = np.array(current_state['delay'])

        if self.use_neighbor_interference:
            neighbor_interference = np.zeros(num_ues)
            for i in range(num_ues):
                left = (i - 1) % num_ues;
                right = (i + 1) % num_ues
                neighbor_allocs = allocs[[left, i, right]]
                neighbor_interference[i] = np.mean(neighbor_allocs) * 0.4
        else:
            neighbor_interference = np.zeros(num_ues)

        next_prb = np.clip(curr_prb * (1 + 0.12 * (allocs - 0.5) + neighbor_interference), 0, 100)
        # REAL PRB overload: percent of UEs above threshold
        real_prb_threshold = 90
        real_prb_viol = np.mean(next_prb > real_prb_threshold) * 100

        channel_gain = np.random.lognormal(0, 0.3, num_ues)
        efficiency = 1.0 / (1 + 0.1 * next_prb / 100)
        next_tput = np.clip(curr_tput * allocs * channel_gain * efficiency + np.random.normal(0, 0.3, num_ues), 0, 50)
        queue_factor = 1 + 0.25 * (1 - allocs) * (curr_tput / (np.mean(curr_tput) + 1e-6))
        next_delay = np.clip(curr_delay * queue_factor + np.random.exponential(0.001, num_ues), 0.001, 0.1)

        lambda_over = 0.8  # tune 5–15
        over_request_penalty = lambda_over * over_per_ue

        tput_reward = np.mean(next_tput) * 3.5
        fairness_bonus = (np.sum(allocs) ** 2) / (num_ues * np.sum(allocs ** 2)) * 4.0
        overload_penalty = np.mean(np.maximum(0, next_prb - 90)) * 1.0 if self.use_prb_overload_penalty else 0.0
        delay_penalty = np.mean(next_delay > 0.01) * 3.0
        reward = tput_reward + fairness_bonus - overload_penalty - delay_penalty-over_request_penalty

        prb_violation= over_request * 100
        return {
            'prb': next_prb.tolist(),
            'tput': next_tput.tolist(),
            'delay': next_delay.tolist(),
            'real_prb_viol': real_prb_viol
        }, reward, prb_violation

def load_testbed_data(cfg: Config, filepath: str = None) -> list:
    if filepath is None:
        filepath = cfg.train_file
    kpm = pd.read_csv(filepath)
    print(f"Loaded {len(kpm)} KPM rows from {filepath}")
    kpm['window'] = np.arange(len(kpm)) // cfg.window_size
    graphs = []
    for _, window in kpm.groupby('window'):
        if len(window) < max(2, cfg.window_size // 2):
            continue
        feat_cols = [
            'RRU.PrbTotDl', 'DRB.UEThpDl', 'DRB.RlcSduDelayDl',
            'DRB.PdcpSduVolumeDL', 'DRB.PdcpSduVolumeUL'
        ]
        feats = window[feat_cols].ffill().fillna(0).values

        feats = RobustScaler().fit_transform(feats).astype(np.float32)
        n = len(feats)
        edges = [[i, (i + 1) % n] for i in range(n)] + [[i, (i + n - 1) % n] for i in range(n)]
        graph = Data(
            x=torch.FloatTensor(feats),
            edge_index=torch.LongTensor(np.array(edges).T),
            prb=window['RRU.PrbTotDl'].fillna(30).values,
            tput=window['DRB.UEThpDl'].fillna(5).values,
            delay=window['DRB.RlcSduDelayDl'].fillna(0.003).values
        )
        graphs.append(graph)
    print(f"Created {len(graphs)} graphs")
    return graphs

def train_labeling_xapp(train_graphs: list, test_graphs: list, cfg: Config, seed: int) -> LabelingxApp:
    set_seeds(seed)
    model = LabelingxApp(5).to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=0.01)
    focal_loss = FocalLoss(gamma=2.0)
    best_acc, best_f1 = 0, 0
    best_path = None

    for epoch in range(cfg.gs_epochs):
        model.train()
        loss_total = 0
        for g in train_graphs:
            prb = g.prb
            y = np.digitize(prb, np.percentile(prb, [33, 66]))
            g.y = torch.LongTensor(y).to(device)
            opt.zero_grad()
            pred = model(g.x.to(device), g.edge_index.to(device))
            loss = focal_loss(pred, g.y)
            loss.backward()
            opt.step()
            loss_total += loss.item()

        if epoch % 20 == 0:
            model.eval()
            all_true, all_pred = [], []
            correct, total = 0, 0
            with torch.no_grad():
                for g in test_graphs:
                    prb = g.prb
                    y_true = np.digitize(prb, np.percentile(prb, [33, 66]))
                    pred = model(g.x.to(device), g.edge_index.to(device)).argmax(1).cpu().numpy()
                    correct += (pred == y_true).sum().item()
                    total += len(y_true)
                    all_true.extend(y_true)
                    all_pred.extend(pred)

            acc = correct / total
            macro_f1 = f1_score(all_true, all_pred, average='macro')
            print(f"[Seed {seed}] Labeling E{epoch}: Loss={loss_total / len(train_graphs):.3f}, "
                  f"Acc={acc:.0%}, Macro-F1={macro_f1:.3f}")

            if macro_f1 > best_f1:
                best_f1 = macro_f1
                best_acc = acc
                best_path = f'labeling_xapp_acc{int(best_acc*100)}_f1{int(best_f1*100)}_seed{seed}.pth'
                torch.save(model.state_dict(), best_path)

    model.load_state_dict(torch.load(best_path))
    print(f"[Seed {seed}] Labeling xApp: {best_f1:.0%} Macro-F1 | {best_acc:.0%} Acc | saved: {best_path}")
    return model


def final_gnn_labeling_evaluation(graphs: list, model: LabelingxApp, split_idx: int = 0, seed: int = 0,
                                  csv_path=None):

    if csv_path is None:
        csv_path = f'final_labeling_results_seed{seed}.csv'

    model.eval()
    all_true, all_pred, all_prb, all_probs = [], [], [], []

    print(f"\n{'=' * 60}")
    print(f"FINAL GNN LABELING EVALUATION [Seed {seed}]")
    print(f"{'=' * 60}")

    with torch.no_grad():
        for g_idx, g in enumerate(graphs[split_idx:]):
            prb = g.prb
            y_true = np.digitize(prb, np.percentile(prb, [33, 66]))

            # Predictions
            logits = model(g.x.to(device), g.edge_index.to(device))
            y_pred = logits.argmax(1).cpu().numpy()
            probs = F.softmax(logits, dim=1).cpu().numpy()

            all_true.extend(y_true)
            all_pred.extend(y_pred)
            all_prb.extend(prb)
            all_probs.extend(probs)

    # Convert to arrays
    all_true = np.array(all_true)
    all_pred = np.array(all_pred)
    all_prb = np.array(all_prb)
    all_probs = np.array(all_probs)

    # Calculate metrics
    accuracy = (all_true == all_pred).mean()
    macro_f1 = f1_score(all_true, all_pred, average='macro')
    weighted_f1 = f1_score(all_true, all_pred, average='weighted')

    print(f"Test Set Size: {len(all_true)} nodes")
    print(f"Accuracy: {accuracy:.1%}")
    print(f"Macro F1: {macro_f1:.3f}")
    print(f"Weighted F1: {weighted_f1:.3f}")

    # Full classification report
    print("\nFULL CLASSIFICATION REPORT:")
    print(classification_report(all_true, all_pred,
                                target_names=['Low PRB', 'Med PRB', 'High PRB']))

    # Confusion Matrix
    cm = confusion_matrix(all_true, all_pred)
    print("\nCONFUSION MATRIX:")
    print(cm)

    # Per-class support
    unique, counts = np.unique(all_true, return_counts=True)
    print("\nCLASS DISTRIBUTION:")
    for cls, count in zip(unique, counts):
        print(f"  Class {cls} (PRB tertile): {count} nodes ({count / len(all_true):.1%})")

    # SAVE COMPREHENSIVE CSV
    results_df = pd.DataFrame({
        'node_id': range(len(all_true)),
        'true_prb': all_prb,
        'true_label': all_true,
        'pred_label': all_pred,
        'pred_prob_0': all_probs[:, 0],
        'pred_prob_1': all_probs[:, 1],
        'pred_prob_2': all_probs[:, 2],
        'pred_max_prob': np.max(all_probs, axis=1),
        'correct': (all_true == all_pred)
    })

    # Add PRB ranges for interpretability
    prb_33, prb_66 = np.percentile(all_prb, [33, 66])
    results_df['true_prb_range'] = pd.cut(results_df['true_prb'],
                                          bins=[-np.inf, prb_33, prb_66, np.inf],
                                          labels=['Low', 'Med', 'High'])

    results_df.to_csv(csv_path, index=False)

    # Summary stats to CSV
    summary_stats = pd.DataFrame({
        'metric': ['accuracy', 'macro_f1', 'weighted_f1', 'total_nodes'],
        'value': [accuracy, macro_f1, weighted_f1, len(all_true)]
    })
    summary_stats.to_csv(csv_path.replace('.csv', '_summary.csv'), index=False)

    print(f"\n✅ DETAILED RESULTS SAVED:")
    print(f"   {csv_path}")
    print(f"   {csv_path.replace('.csv', '_summary.csv')}")

    # Confusion matrix plot
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Low', 'Med', 'High'],
                yticklabels=['Low', 'Med', 'High'])
    plt.title(f'GNN Labeling Confusion Matrix [Seed {seed}]\nAcc={accuracy:.1%} | Macro-F1={macro_f1:.3f}')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.tight_layout()
    plt.savefig(f'plots/labeling_cm_seed{seed}.png', dpi=300, bbox_inches='tight')
    plt.close()
    print(f"   Confusion matrix plot: plots/labeling_cm_seed{seed}.png")

    return {
        'accuracy': accuracy,
        'macro_f1': macro_f1,
        'weighted_f1': weighted_f1,
        'cm': cm,
        'df': results_df
    }


def prepare_flat_node_dataset(train_graphs: list, test_graphs: list):
    def extract(graphs):
        X_list, y_list = [], []
        for g in graphs:
            prb = g.prb
            y = np.digitize(prb, np.percentile(prb, [33, 66]))
            X_list.append(g.x.cpu().numpy())
            y_list.append(y)
        X = np.concatenate(X_list, axis=0) if X_list else np.empty((0, 5))
        y = np.concatenate(y_list, axis=0) if y_list else np.empty((0,))
        return X, y
    return (*extract(train_graphs), *extract(test_graphs))


def train_eval_sklearn_baselines(X_train, y_train, X_test, y_test, seed: int, out_prefix="baseline", save_csv=True):
    y_train = y_train.astype(int)
    y_test = y_test.astype(int)

    X_train = np.nan_to_num(X_train, copy=False)
    X_test  = np.nan_to_num(X_test,  copy=False)

    results = []

    try:
        lr = LogisticRegression(
            max_iter=1000,
            solver='lbfgs',
            class_weight='balanced',
            random_state=seed
        )
        lr.fit(X_train, y_train)
        y_pred = lr.predict(X_test)
        macro_f1 = f1_score(y_test, y_pred, average='macro')
        acc = (y_test == y_pred).mean()
        results.append({"model": "LogReg", "acc": acc, "macro_f1": macro_f1})
        lr_path = f'logreg_acc{int(acc*100)}_f1{int(macro_f1*100)}_seed{seed}.pkl'
        joblib.dump(lr, lr_path)
        print(f"✅ LogReg model saved: {lr_path}")
    except Exception as e:
        print(f"⚠️ LogisticRegression failed: {e}")

    # Convert to DataFrame and SAVE
    df = pd.DataFrame(results)
    if save_csv:
        df.to_csv(f"{out_prefix}_sklearn_seed{seed}.csv", index=False)
        print(f"✅ Sklearn baselines saved: {out_prefix}_sklearn_seed{seed}.csv")

    return df


def run_labeling_baselines(train_graphs: list, test_graphs: list, cfg: Config, seed: int, gsage_model: LabelingxApp):
    print("\n" + "="*60)
    print(f"LABELING BASELINES COMPARISON [Seed {seed}]")
    print("="*60)

    from sklearn.preprocessing import StandardScaler

    # 1) Flat dataset for non-graph baselines
    X_train, y_train, X_test, y_test = prepare_flat_node_dataset(train_graphs, test_graphs)
    print(f"Flat dataset: X_train={X_train.shape}, X_test={X_test.shape}")

    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    # 2) Sklearn baselines
    sk_df = train_eval_sklearn_baselines(X_train, y_train, X_test, y_test, seed, out_prefix="labeling_baselines")

    # 3) GCN baseline (graph)
    gcn_model = GCNLabelingxApp(in_dim=train_graphs[0].x.shape[1])
    gcn_model = train_graph_labeler(train_graphs, test_graphs, gcn_model, cfg, seed, lr=0.01, every=20, tag="GCN")
    gcn_eval = final_gnn_labeling_evaluation(test_graphs, gcn_model, split_idx=0, seed=seed, csv_path=f'gcn_labeling_results_seed{seed}.csv')

    # 4) GraphSAGE results already computed
    gsage_eval = final_gnn_labeling_evaluation(test_graphs, gsage_model, split_idx=0, seed=seed, csv_path=f'graphsage_labeling_results_seed{seed}.csv')

    # 5) Consolidate comparison table
    rows = []
    for _, r in sk_df.iterrows():
        rows.append({"Model": r["model"], "Accuracy": r.get("acc", np.nan), "Macro_F1": r.get("macro_f1", np.nan)})
    rows.append({"Model": "GCN", "Accuracy": gcn_eval['accuracy'], "Macro_F1": gcn_eval['macro_f1']})
    rows.append({"Model": "GraphSAGE", "Accuracy": gsage_eval['accuracy'], "Macro_F1": gsage_eval['macro_f1']})

    comp = pd.DataFrame(rows)
    comp.to_csv(f"labeling_models_comparison_seed{seed}.csv", index=False)
    print("\n" + "-"*60)
    print(f"MODEL COMPARISON [Seed {seed}]\n{comp}")
    print(f"✅ Saved: labeling_models_comparison_seed{seed}.csv")
    print("-"*60)
    return comp

def run_once(cfg: Config, seed: int):
    train_graphs = load_testbed_data(cfg, filepath=cfg.train_file)
    test_graphs  = load_testbed_data(cfg, filepath=cfg.test_file)
    print(f"Train graphs: {len(train_graphs)} | Test graphs: {len(test_graphs)}")

    print(f"\n[Seed {seed}] Training Labeling xApp...")
    label_xapp = train_labeling_xapp(train_graphs, test_graphs, cfg, seed)

    labeling_results = final_gnn_labeling_evaluation(test_graphs, label_xapp, split_idx=0, seed=seed)

    _ = run_labeling_baselines(train_graphs, test_graphs, cfg, seed, gsage_model=label_xapp)

    return labeling_results

def main(cfg: Config):
    print("Training Stability + Graph Ablations + Macro-F1 + Multi-Seed Stats")

    seeds = [42, 123, 456][:cfg.n_seeds]
    all_summaries = []
    all_full_rewards = []

    for seed in seeds:
        print(f"\n{'=' * 80}")
        print(f"RUNNING SEED {seed}")
        print(f"{'=' * 80}")
        summary = run_once(cfg, seed)
        all_summaries.append(summary)

        # Extract full model reward
        full_key = 'O-RAN (GNN+DDQN)[Full]'
        if full_key in summary.index:
            reward = float(summary.loc[full_key, 'Reward↑'])
            all_full_rewards.append(reward)

    if all_full_rewards:
        mean_r, std_r = np.mean(all_full_rewards), np.std(all_full_rewards)
        print(f"\n O-RAN Full (GNN+DDQN): {mean_r:.2f} ± {std_r:.2f}")

    print("Per-seed: scientific_results_seed*.csv")
    print("AGGREGATED: FINAL_results_mean_std.csv")
    print("Plots: plots/FINAL_ablation_comparison.png + ablation_seed*.png")

def main(cfg: Config):
    print("Training Stability + Graph Ablations + Macro-F1 + Multi-Seed Stats")

    seeds = [42, 123, 456][:cfg.n_seeds]
    all_summaries = []
    all_full_rewards = []

    for seed in seeds:
        print(f"\n{'=' * 80}")
        print(f"RUNNING SEED {seed}")
        print(f"{'=' * 80}")

        labeling_results = run_once(cfg, seed)

    print("Per-seed: scientific_results_seed*.csv")
    print("GNN Labeling: final_labeling_results_seed*.csv")

if __name__ == "__main__":
    main(cfg)