# -*- coding: utf-8 -*-
"""inference_smart_manufacturing_intra_UE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hXMsmPsa7fLZNxnKgHRkNeJS-CsSDQsD

# O-RAN Dual xApps Inference Notebook

**Fix:** Matched state construction exactly to training code.

**State composition (8 dimensions):**
1. Load prediction (integer class)
2. Normalized PRB (prb/100)
3. Normalized throughput (tput/20)
4. Normalized delay (delay/0.01)
5. First embedding dimension only
6. PRB * 0.1
7. Throughput * 0.1
8. Delay * 0.1

**Date:** 2026-01-30
"""

!pip install -q torch-geometric

import os
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.nn import SAGEConv
from sklearn.preprocessing import RobustScaler
import matplotlib.pyplot as plt
import seaborn as sns
from typing import Union, List, Dict
import warnings

warnings.filterwarnings('ignore')

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

"""## Model Definitions"""

class LabelingxApp(nn.Module):
    """GNN model for load classification"""
    def __init__(self, in_dim: int, hidden_dim: int = 64):
        super().__init__()
        self.conv1 = SAGEConv(in_dim, hidden_dim)
        self.conv2 = SAGEConv(hidden_dim, hidden_dim)
        self.conv3 = SAGEConv(hidden_dim, hidden_dim // 2)
        self.bn1 = nn.BatchNorm1d(hidden_dim)
        self.bn2 = nn.BatchNorm1d(hidden_dim)
        self.bn3 = nn.BatchNorm1d(hidden_dim // 2)
        self.dropout = nn.Dropout(0.2)
        self.load_head = nn.Sequential(
            nn.Linear(hidden_dim // 2, 32),
            nn.ReLU(),
            nn.Linear(32, 3)
        )
        self.embeddings = None

    def forward(self, x, edge_index):
        h = F.relu(self.bn1(self.conv1(x, edge_index)))
        h = F.relu(self.bn2(self.conv2(h, edge_index)))
        h = F.relu(self.bn3(self.conv3(h, edge_index)))
        h = self.dropout(h)
        self.embeddings = h.detach()
        return self.load_head(h)


class ResourcexApp:
    """DDQN model for PRB allocation"""
    def __init__(self):
        self.action_dim = 3
        # State: 8 dimensions (load, prb, tput, delay, emb_dim, prb*0.1, tput*0.1, delay*0.1)
        self.q_net = nn.Sequential(
            nn.Linear(8, 128), nn.ReLU(), nn.Dropout(0.1),
            nn.Linear(128, 64), nn.ReLU(),
            nn.Linear(64, 3)
        )

    def act(self, state, epsilon=0.0):
        if np.random.rand() < epsilon:
            return np.random.randint(self.action_dim)
        state = torch.FloatTensor(state).unsqueeze(0)
        with torch.no_grad():
            return self.q_net(state).argmax().item()

print("✓ Models defined")

"""## Data Preprocessor"""

class KPMPreprocessor:
    def __init__(self):
        self.scaler = RobustScaler()
        self.fitted = False
        self.feature_cols = [
            'RRU.PrbTotDl',
            'DRB.UEThpDl',
            'DRB.RlcSduDelayDl',
            'DRB.PdcpSduVolumeDL',
            'DRB.PdcpSduVolumeUL'
        ]

    def fit(self, data: Union[pd.DataFrame, str]):
        if isinstance(data, str):
            df = pd.read_csv(data)
        else:
            df = data

        features = df[self.feature_cols].fillna(method='ffill').fillna(0).values
        self.scaler.fit(features)
        self.fitted = True
        print(f"✓ Scaler fitted on {len(df)} samples")

    def transform_to_graph(self, data: Union[pd.DataFrame, np.ndarray, dict]) -> Data:
        if not self.fitted:
            raise ValueError("Scaler not fitted! Call fit() first.")

        if isinstance(data, dict):
            features = data['features']
            prb = data.get('prb', np.full(len(features), 30.0))
            tput = data.get('tput', np.full(len(features), 5.0))
            delay = data.get('delay', np.full(len(features), 0.003))
        elif isinstance(data, np.ndarray):
            if data.shape[1] != 5:
                raise ValueError(f"Expected 5 features, got {data.shape[1]}")
            features = data
            prb = features[:, 0]
            tput = features[:, 1]
            delay = features[:, 2]
        elif isinstance(data, pd.DataFrame):
            features = data[self.feature_cols].fillna(method='ffill').fillna(0).values
            prb = data['RRU.PrbTotDl'].fillna(30).values
            tput = data['DRB.UEThpDl'].fillna(5).values
            delay = data['DRB.RlcSduDelayDl'].fillna(0.003).values
        else:
            raise ValueError(f"Unsupported data type: {type(data)}")

        features_scaled = self.scaler.transform(features).astype(np.float32)

        n = len(features_scaled)
        edges = []
        for i in range(n):
            edges.append([i, (i + 1) % n])
            edges.append([i, (i + n - 1) % n])

        graph = Data(
            x=torch.FloatTensor(features_scaled),
            edge_index=torch.LongTensor(np.array(edges).T),
            prb=prb,
            tput=tput,
            delay=delay
        )

        return graph

print("✓ Preprocessor defined")

"""## Inference Engine"""

class ORANInferenceEngine:
    def __init__(self):
        self.labeling_xapp = None
        self.resource_xapp = None
        self.preprocessor = KPMPreprocessor()
        self.action_map = {0: 0.2, 1: 0.5, 2: 0.8}
        self.load_labels = ['Light', 'Medium', 'Heavy']
        self.device = device

    def load_models(self, labeling_path: str, resource_path: str):
        print(f"Loading models...")

        # Load LabelingxApp
        self.labeling_xapp = LabelingxApp(in_dim=5).to(self.device)
        checkpoint = torch.load(labeling_path, map_location=self.device)
        if isinstance(checkpoint, dict) and 'model_state_dict' in checkpoint:
            self.labeling_xapp.load_state_dict(checkpoint['model_state_dict'])
        else:
            self.labeling_xapp.load_state_dict(checkpoint)
        self.labeling_xapp.eval()
        print(f"  ✓ LabelingxApp loaded")

        # Load ResourcexApp
        self.resource_xapp = ResourcexApp()
        checkpoint = torch.load(resource_path, map_location=self.device)
        if isinstance(checkpoint, dict) and 'model_state_dict' in checkpoint:
            self.resource_xapp.q_net.load_state_dict(checkpoint['model_state_dict'])
        else:
            self.resource_xapp.q_net.load_state_dict(checkpoint)
        self.resource_xapp.q_net.eval()
        print(f"  ✓ ResourcexApp loaded (state_dim=8)")

    def fit_preprocessor(self, historical_data: Union[pd.DataFrame, str]):
        self.preprocessor.fit(historical_data)

    def predict(self, data: Union[pd.DataFrame, np.ndarray, dict], verbose: bool = True) -> Dict:
        if self.labeling_xapp is None or self.resource_xapp is None:
            raise ValueError("Models not loaded! Call load_models() first.")

        graph = self.preprocessor.transform_to_graph(data)
        num_ues = len(graph.x)

        # Stage 1: LabelingxApp (GNN classification)
        with torch.no_grad():
            logits = self.labeling_xapp(graph.x, graph.edge_index)
            load_predictions = logits.argmax(dim=1).cpu().numpy()  # Class indices (0, 1, 2)
            embeddings = self.labeling_xapp.embeddings.cpu().numpy()  # Shape: (num_ues, 32)

        # Extract metrics from graph
        prb = graph.prb
        tput = graph.tput
        delay = graph.delay

        # Normalize metrics (MATCHING TRAINING CODE)
        prb_norm = prb / 100.0
        tput_norm = tput / 20.0
        delay_norm = delay / 0.01
        emb_dim = embeddings[:, 0]  # CRITICAL: Only use first embedding dimension!

        # Construct RL states (EXACTLY AS IN TRAINING)
        # State: [load_pred, prb_norm, tput_norm, delay_norm, emb_dim, prb*0.1, tput*0.1, delay*0.1]
        states = np.column_stack([
            load_predictions,   # 1D: class index (0, 1, or 2)
            prb_norm,           # 1D: normalized PRB
            tput_norm,          # 1D: normalized throughput
            delay_norm,         # 1D: normalized delay
            emb_dim,            # 1D: first embedding dimension
            prb_norm * 0.1,     # 1D: scaled PRB
            tput_norm * 0.1,    # 1D: scaled throughput
            delay_norm * 0.1    # 1D: scaled delay
        ])  # Shape: (num_ues, 8)

        if verbose:
            print(f"DEBUG: States shape = {states.shape}")  # Should be (num_ues, 8)
            print(f"DEBUG: First state = {states[0]}")

        # Stage 2: ResourcexApp (RL allocation)
        actions = []
        for i in range(num_ues):
            action = self.resource_xapp.act(states[i], epsilon=0.0)
            actions.append(action)

        # Convert actions to allocations
        allocations = [self.action_map[a] for a in actions]
        total_alloc = sum(allocations)
        if total_alloc > 1.0:
            allocations = [a / total_alloc for a in allocations]

        results = {
            'load_labels': [self.load_labels[p] for p in load_predictions],
            'load_predictions': load_predictions,
            'actions': actions,
            'allocations': allocations,
            'embeddings': embeddings,
            'states': states,
            'prb': prb,
            'tput': tput,
            'delay': delay,
            'num_ues': num_ues
        }

        if verbose:
            self._print_results(results)

        return results

    def _print_results(self, results: Dict):
      print("\n" + "="*90)
      print("O-RAN DUAL xAPPS INFERENCE RESULTS")
      print("="*90)
      print(f"Number of UEs: {results['num_ues']}")
      print("-"*90)
      print(f"{'UE':<4} {'Load':<8} {'Action':<8} {'Allocation':<12} {'PRB':<10} {'Thput':<12} {'Delay':<12}")
      print("-"*90)

      for i in range(results['num_ues']):
          print(f"{i:<4} "
                f"{results['load_labels'][i]:<8} "
                f"{results['actions'][i]:<8} "
                f"{results['allocations'][i]:<12.1%} "
                f"{results['prb'][i]:<10.1f} "
                f"{results['tput'][i]:<12.2f} "
                f"{results['delay'][i]:<12.4f}")

      print("-"*90)
      print(f"Total Allocation: {sum(results['allocations']):.1%}")
      print("="*90 + "\n")

print("✓ Inference engine defined")

"""## Load Models and Fit Preprocessor"""

engine = ORANInferenceEngine()

# CONFIGURE THESE PATHS
LABELING_MODEL_PATH = '/content/labeling_xapp_seed123.pth'
RESOURCE_MODEL_PATH = '/content/resource_xapp_seed123.pth'

"""## Split data, only use this to split the data by UE. This does not clean data."""

"""
Smart Manufacturing KPM Data Preprocessing
===========================================

Simple preprocessing: Split KPM data by UE ranges only.
Then save the csv for per UE.

"""

import pandas as pd
import numpy as np
from typing import Dict, Tuple
import warnings
warnings.filterwarnings('ignore')


# UE range definitions per file
UE_RANGES = {
    'embb': {
        3: (0, 791),
        4: (791, 1936),
        5: (1936, None)  # None means to the end
    },
    'mmtc': {
        1: (0, 1114),
        2: (1114, 2144),
        3: (2144, 3254),
        4: (3254, 3774),
        5: (3774, None)
    },
    'urllc': {
        1: (0, 1744),
        2: (1744, 3114),
        3: (3114, 3599),
        4: (3599, 3674),
        5: (3674, None)
    }
}


def split_by_ue(df: pd.DataFrame, slice_name: str) -> Dict[int, pd.DataFrame]:
    """
    Split KPM data by UE based on predefined ranges

    Parameters
    ----------
    df : pd.DataFrame
        Input KPM dataframe
    slice_name : str
        'embb', 'mmtc', or 'urllc'

    Returns
    -------
    ue_data : dict
        Dictionary mapping UE_ID → DataFrame

    Example
    -------
    >>> embb = pd.read_csv("oai-kpm-2026-02-23-085959-embb.csv")
    >>> ue_data = split_by_ue(embb, 'embb')
    >>> ue3_data = ue_data[3]  # Data for UE 3
    """
    if slice_name not in UE_RANGES:
        raise ValueError(f"Unknown slice: {slice_name}. Must be 'embb', 'mmtc', or 'urllc'")

    ue_data = {}
    ranges = UE_RANGES[slice_name]

    print(f"\nSplitting {slice_name.upper()} by UE:")
    for ue_id, (start, end) in ranges.items():
        if end is None:
            ue_df = df.iloc[start:].copy().reset_index(drop=True)
        else:
            ue_df = df.iloc[start:end].copy().reset_index(drop=True)

        ue_data[ue_id] = ue_df
        print(f"  UE {ue_id}: rows {start:5d}-{end if end else 'end':>5} → {len(ue_df):5d} samples")

    return ue_data


def load_and_split(embb_path: str, mmtc_path: str, urllc_path: str) -> Dict[str, Dict[int, pd.DataFrame]]:
    """
    Load all KPM files and split by UE

    Parameters
    ----------
    embb_path : str
        Path to eMBB KPM CSV
    mmtc_path : str
        Path to mMTC KPM CSV
    urllc_path : str
        Path to URLLC KPM CSV

    Returns
    -------
    all_data : dict
        Nested dictionary: slice_name → {UE_ID → DataFrame}

    Example
    -------
    >>> data = load_and_split('embb.csv', 'mmtc.csv', 'urllc.csv')
    >>> embb_ue3 = data['embb'][3]
    >>> mmtc_ue1 = data['mmtc'][1]
    >>> urllc_ue2 = data['urllc'][2]
    """
    print("Loading KPM files...")

    # Load data
    embb = pd.read_csv(embb_path)
    mmtc = pd.read_csv(mmtc_path)
    urllc = pd.read_csv(urllc_path)

    print(f"  ✓ eMBB:  {len(embb):6d} rows")
    print(f"  ✓ mMTC:  {len(mmtc):6d} rows")
    print(f"  ✓ URLLC: {len(urllc):6d} rows")

    # Split by UE
    all_data = {
        'embb': split_by_ue(embb, 'embb'),
        'mmtc': split_by_ue(mmtc, 'mmtc'),
        'urllc': split_by_ue(urllc, 'urllc')
    }

    return all_data


# =============================================================================
# USAGE EXAMPLE
# =============================================================================

if __name__ == "__main__":
    # Example 1: Load and split all at once
    data = load_and_split(
        embb_path='/content/oai-kpm-2026-02-23-085959-embb.csv',
        mmtc_path='/content/oai-kpm-2026-02-23-092029-mmtc.csv',
        urllc_path='/content/oai-kpm-2026-02-23-094231-urllc.csv'
    )

    # Access specific UE data
    embb_ue3 = data['embb'][3]
    mmtc_ue1 = data['mmtc'][1]
    urllc_ue5 = data['urllc'][5]

    print(f"\nExample access:")
    print(f"  eMBB UE 3: {len(embb_ue3)} rows")
    print(f"  mMTC UE 1: {len(mmtc_ue1)} rows")
    print(f"  URLLC UE 5: {len(urllc_ue5)} rows")

embb, mmtc, urllc = data['embb'], data['mmtc'], data['urllc']

# for i in range(3, 6):
#   embb[i].to_csv(f"embb_ue{i}.csv", index=0)

# for i in range(1, 6):
#   mmtc[i].to_csv(f"mmtc_ue{i}.csv", index=0)
#   urllc[i].to_csv(f"urllc_ue{i}.csv", index=0)

"""## Load input per UE per slice. This data is manually cleaned."""

embb_ue3 = pd.read_csv('/content/embb_ue3.csv')
embb_ue4 = pd.read_csv('/content/embb_ue4.csv')
embb_ue5 = pd.read_csv('/content/embb_ue5.csv')


mmtc_ue1 = pd.read_csv('/content/mmtc_ue1.csv')
mmtc_ue2 = pd.read_csv('/content/mmtc_ue2.csv')
mmtc_ue3 = pd.read_csv('/content/mmtc_ue3.csv')
mmtc_ue4 = pd.read_csv('/content/mmtc_ue4.csv')
mmtc_ue5 = pd.read_csv('/content/mmtc_ue5.csv')


urllc_ue1 = pd.read_csv('/content/urllc_ue1.csv')
urllc_ue2 = pd.read_csv('/content/urllc_ue2.csv')
urllc_ue3 = pd.read_csv('/content/urllc_ue3.csv')
urllc_ue4 = pd.read_csv('/content/urllc_ue4.csv')
urllc_ue5 = pd.read_csv('/content/urllc_ue5.csv')

embb_test  = pd.read_csv('embb_test.csv')
mmtc_test  = pd.read_csv('mmtc_test.csv')
urllc_test = pd.read_csv('urllc_test.csv')

"""## Run Inference separate model per slice"""

# Run inference
results = engine.predict(embb_test.iloc[0:5], verbose=True)

embb_test.iloc[0:5]

def add_inference_results(df, engine, verbose=False):
    """
    Run inference on every 5 rows and add results as new columns.

    Parameters
    ----------
    df : pd.DataFrame
        Single UE dataframe (e.g., embb_ue3)
    engine : ORANInferenceEngine
        Inference engine with predict method
    verbose : bool
        Whether to show inference progress

    Returns
    -------
    df_with_results : pd.DataFrame
        DataFrame with added columns: pred_load_label, pred_action, pred_allocation
    """
    # Initialize lists to store results
    load_labels_list = []
    actions_list = []
    allocations_list = []

    # Process in batches of 5 rows
    num_batches = len(df) // 5

    for i in range(num_batches):
        start_idx = i * 5
        end_idx = start_idx + 5
        batch = df.iloc[start_idx:end_idx]

        # Run inference
        results = engine.predict(batch, verbose=verbose)

        # Extract and store results
        load_labels_list.extend(results['load_labels'])
        actions_list.extend(results['actions'])
        allocations_list.extend(results['allocations'])

    # Handle remaining rows if not divisible by 5
    remaining_rows = len(df) % 5
    if remaining_rows > 0:
        print(f"Warning: {remaining_rows} rows at the end were not processed (not a full batch of 5)")

    # Create result dataframe (only processed rows)
    df_with_results = df.iloc[:num_batches * 5].copy()
    df_with_results['pred_load_label'] = load_labels_list
    df_with_results['pred_action'] = actions_list
    df_with_results['pred_allocation'] = allocations_list

    return df_with_results

print("\n✓ Ready for inference!")
LABELING_MODEL_PATH = '/content/labeling_xapp_embb_seed456.pth'
RESOURCE_MODEL_PATH = '/content/resource_xapp_embb_seed456.pth'
# Process each UE from eMBB slice
HISTORICAL_DATA_PATH = '/content/oai-kpm-2026-02-23-085959-embb.csv'
engine.load_models(LABELING_MODEL_PATH, RESOURCE_MODEL_PATH)
engine.fit_preprocessor(HISTORICAL_DATA_PATH)

embb_test_results = add_inference_results(embb_test, engine, verbose=False)

# Process each UE from mMTC slice
LABELING_MODEL_PATH = '/content/labeling_xapp_mmtc_seed456.pth'
RESOURCE_MODEL_PATH = '/content/resource_xapp_mmtc_seed456.pth'
HISTORICAL_DATA_PATH = '/content/oai-kpm-2026-02-23-092029-mmtc.csv'
engine.load_models(LABELING_MODEL_PATH, RESOURCE_MODEL_PATH)
engine.fit_preprocessor(HISTORICAL_DATA_PATH)

mmtc_test_results = add_inference_results(mmtc_test, engine, verbose=False)

# Process each UE from URLLC slice
LABELING_MODEL_PATH = '/content/labeling_xapp_urllc_seed123.pth'
RESOURCE_MODEL_PATH = '/content/resource_xapp_urllc_seed123.pth'
HISTORICAL_DATA_PATH = '/content/oai-kpm-2026-02-23-094231-urllc.csv'
engine.load_models(LABELING_MODEL_PATH, RESOURCE_MODEL_PATH)
engine.fit_preprocessor(HISTORICAL_DATA_PATH)

urllc_test_results = add_inference_results(urllc_test, engine, verbose=False)

# View results
embb_test_results[['ran_ue_id', 'pred_load_label', 'pred_action', 'pred_allocation',
                  'RRU.PrbTotDl', 'DRB.UEThpDl', 'DRB.RlcSduDelayDl']].head(10)

embb_test_results[['ran_ue_id', 'pred_load_label', 'pred_action', 'pred_allocation',
                  'RRU.PrbTotDl', 'DRB.UEThpDl', 'DRB.RlcSduDelayDl']].head(100)

"""## Run Inference"""

# Run inference
results = engine.predict(embb_ue3.iloc[0:5], verbose=True)

embb_ue3.iloc[0:5]

def add_inference_results(df, engine, verbose=False):
    """
    Run inference on every 5 rows and add results as new columns.

    Parameters
    ----------
    df : pd.DataFrame
        Single UE dataframe (e.g., embb_ue3)
    engine : ORANInferenceEngine
        Inference engine with predict method
    verbose : bool
        Whether to show inference progress

    Returns
    -------
    df_with_results : pd.DataFrame
        DataFrame with added columns: pred_load_label, pred_action, pred_allocation
    """
    # Initialize lists to store results
    load_labels_list = []
    actions_list = []
    allocations_list = []

    # Process in batches of 5 rows
    num_batches = len(df) // 5

    for i in range(num_batches):
        start_idx = i * 5
        end_idx = start_idx + 5
        batch = df.iloc[start_idx:end_idx]

        # Run inference
        results = engine.predict(batch, verbose=verbose)

        # Extract and store results
        load_labels_list.extend(results['load_labels'])
        actions_list.extend(results['actions'])
        allocations_list.extend(results['allocations'])

    # Handle remaining rows if not divisible by 5
    remaining_rows = len(df) % 5
    if remaining_rows > 0:
        print(f"Warning: {remaining_rows} rows at the end were not processed (not a full batch of 5)")

    # Create result dataframe (only processed rows)
    df_with_results = df.iloc[:num_batches * 5].copy()
    df_with_results['pred_load_label'] = load_labels_list
    df_with_results['pred_action'] = actions_list
    df_with_results['pred_allocation'] = allocations_list

    return df_with_results

print("\n✓ Ready for inference!")
LABELING_MODEL_PATH = '/content/labeling_xapp_seed123.pth'
RESOURCE_MODEL_PATH = '/content/resource_xapp_seed123.pth'
# Process each UE from eMBB slice
HISTORICAL_DATA_PATH = '/content/oai-kpm-2026-02-23-085959-embb.csv'
engine.load_models(LABELING_MODEL_PATH, RESOURCE_MODEL_PATH)
engine.fit_preprocessor(HISTORICAL_DATA_PATH)

embb_ue3_results = add_inference_results(embb_ue3, engine, verbose=False)
embb_ue4_results = add_inference_results(embb_ue4, engine, verbose=False)
embb_ue5_results = add_inference_results(embb_ue5, engine, verbose=False)

# Process each UE from mMTC slice
HISTORICAL_DATA_PATH = '/content/oai-kpm-2026-02-23-092029-mmtc.csv'
engine.load_models(LABELING_MODEL_PATH, RESOURCE_MODEL_PATH)
engine.fit_preprocessor(HISTORICAL_DATA_PATH)

mmtc_ue1_results = add_inference_results(mmtc_ue1, engine, verbose=False)
mmtc_ue2_results = add_inference_results(mmtc_ue2, engine, verbose=False)
mmtc_ue3_results = add_inference_results(mmtc_ue3, engine, verbose=False)
mmtc_ue4_results = add_inference_results(mmtc_ue4, engine, verbose=False)
mmtc_ue5_results = add_inference_results(mmtc_ue5, engine, verbose=False)

# Process each UE from URLLC slice
HISTORICAL_DATA_PATH = '/content/oai-kpm-2026-02-23-094231-urllc.csv'
engine.load_models(LABELING_MODEL_PATH, RESOURCE_MODEL_PATH)
engine.fit_preprocessor(HISTORICAL_DATA_PATH)

urllc_ue1_results = add_inference_results(urllc_ue1, engine, verbose=False)
urllc_ue2_results = add_inference_results(urllc_ue2, engine, verbose=False)
urllc_ue3_results = add_inference_results(urllc_ue3, engine, verbose=False)
urllc_ue4_results = add_inference_results(urllc_ue4, engine, verbose=False)
urllc_ue5_results = add_inference_results(urllc_ue5, engine, verbose=False)

# View results
embb_ue3_results[['ran_ue_id', 'pred_load_label', 'pred_action', 'pred_allocation',
                  'RRU.PrbTotDl', 'DRB.UEThpDl', 'DRB.RlcSduDelayDl']].head(10)

embb_ue4_results[['ran_ue_id', 'pred_load_label', 'pred_action', 'pred_allocation',
                  'RRU.PrbTotDl', 'DRB.UEThpDl', 'DRB.RlcSduDelayDl']].head(100)

"""## Full Report"""

"""
Inference Report Generator for O-RAN Dual xApps
================================================

Generates detailed analysis reports for inference results including:
- Prediction statistics
- Feature distribution analysis
- Prediction correctness validation
- Anomaly detection
"""

import pandas as pd
import numpy as np
from typing import Dict, List, Tuple


def generate_inference_report(results_df: pd.DataFrame,
                              ue_name: str,
                              slice_type: str) -> None:
    """
    Generate comprehensive inference report with statistics and insights

    Parameters
    ----------
    results_df : pd.DataFrame
        DataFrame with inference results (output from add_inference_results)
    ue_name : str
        UE identifier (e.g., 'UE3', 'UE1')
    slice_type : str
        Slice type: 'eMBB', 'mMTC', or 'URLLC'
    """
    print("="*90)
    print(f"INFERENCE REPORT: {slice_type} - {ue_name}")
    print("="*90)

    # 1. Basic Statistics
    print_basic_statistics(results_df)

    # 2. Prediction Distribution
    print_prediction_distribution(results_df)

    # 3. Feature Analysis
    print_feature_statistics(results_df)

    # 4. Prediction Validation
    print_prediction_validation(results_df, slice_type)

    # 5. Anomaly Detection
    print_anomalies(results_df)

    # 6. Action-Load Consistency
    print_action_load_consistency(results_df)

    print("="*90 + "\n")


def print_basic_statistics(df: pd.DataFrame):
    """Print basic statistics about the dataset"""
    print(f"\n{'─'*90}")
    print("1. BASIC STATISTICS")
    print(f"{'─'*90}")
    print(f"Total samples:           {len(df)}")
    print(f"Number of windows:       {len(df) // 5}")
    print(f"Unique UE IDs:           {df['ran_ue_id'].nunique() if 'ran_ue_id' in df.columns else 'N/A'}")

    # Check for potential idle rows
    idle_rows = df[(df['DRB.UEThpDl'] == 0) &
                   (df['DRB.PdcpSduVolumeDL'] == 0) &
                   (df['DRB.PdcpSduVolumeUL'] == 0)]
    if len(idle_rows) > 0:
        print(f"⚠️  Idle rows detected:    {len(idle_rows)} ({len(idle_rows)/len(df):.1%})")


def print_prediction_distribution(df: pd.DataFrame):
    """Print prediction distribution statistics"""
    print(f"\n{'─'*90}")
    print("2. PREDICTION DISTRIBUTION")
    print(f"{'─'*90}")

    # Load label distribution
    print("\n📊 Load Label Distribution:")
    print(f"{'Label':<10} {'Count':>8} {'Percentage':>12}")
    print(f"{'-'*32}")

    load_counts = df['pred_load_label'].value_counts()
    for label in ['Light', 'Medium', 'Heavy']:
        count = load_counts.get(label, 0)
        pct = count / len(df) * 100
        print(f"{label:<10} {count:>8} {pct:>11.1f}%")

    # Action distribution
    print(f"\n📊 Action Distribution:")
    print(f"{'Action':<10} {'Allocation':>12} {'Count':>8} {'Percentage':>12}")
    print(f"{'-'*44}")

    action_map = {0: '20%', 1: '50%', 2: '80%'}
    action_counts = df['pred_action'].value_counts()
    for action in [0, 1, 2]:
        count = action_counts.get(action, 0)
        pct = count / len(df) * 100
        print(f"{action:<10} {action_map[action]:>12} {count:>8} {pct:>11.1f}%")

    # Allocation statistics
    print(f"\n📊 Allocation Statistics:")
    print(f"  Mean allocation:     {df['pred_allocation'].mean():.1%}")
    print(f"  Median allocation:   {df['pred_allocation'].median():.1%}")
    print(f"  Min allocation:      {df['pred_allocation'].min():.1%}")
    print(f"  Max allocation:      {df['pred_allocation'].max():.1%}")


def print_feature_statistics(df: pd.DataFrame):
    """Print feature statistics"""
    print(f"\n{'─'*90}")
    print("3. FEATURE STATISTICS")
    print(f"{'─'*90}")

    features = {
        'RRU.PrbTotDl': 'PRB DL (%)',
        'DRB.UEThpDl': 'Throughput DL (Mbps)',
        'DRB.RlcSduDelayDl': 'Delay DL (ms)',
        'DRB.PdcpSduVolumeDL': 'Volume DL',
        'DRB.PdcpSduVolumeUL': 'Volume UL'
    }

    print(f"\n{'Feature':<25} {'Mean':>12} {'Median':>12} {'Min':>12} {'Max':>12}")
    print(f"{'-'*75}")

    for col, label in features.items():
        if col in df.columns:
            mean_val = df[col].mean()
            median_val = df[col].median()
            min_val = df[col].min()
            max_val = df[col].max()
            print(f"{label:<25} {mean_val:>12.2f} {median_val:>12.2f} {min_val:>12.2f} {max_val:>12.2f}")


def print_prediction_validation(df: pd.DataFrame, slice_type: str):
    """Validate predictions against expected behavior"""
    print(f"\n{'─'*90}")
    print("4. PREDICTION VALIDATION")
    print(f"{'─'*90}")

    # Define thresholds for "low activity" features
    LOW_THRESHOLDS = {
        'RRU.PrbTotDl': 20,
        'DRB.UEThpDl': 10,
        'DRB.RlcSduDelayDl': 50,  # 50ms
        'DRB.PdcpSduVolumeDL': 100,
        'DRB.PdcpSduVolumeUL': 100
    }

    # Find rows with low activity but predicted as Heavy/Medium
    low_activity_mask = (
        (df['RRU.PrbTotDl'] < LOW_THRESHOLDS['RRU.PrbTotDl']) &
        (df['DRB.UEThpDl'] < LOW_THRESHOLDS['DRB.UEThpDl']) &
        (df['DRB.PdcpSduVolumeDL'] < LOW_THRESHOLDS['DRB.PdcpSduVolumeDL']) &
        (df['DRB.PdcpSduVolumeUL'] < LOW_THRESHOLDS['DRB.PdcpSduVolumeUL'])
    )

    suspicious_heavy = df[low_activity_mask & (df['pred_load_label'] == 'Heavy')]
    suspicious_medium = df[low_activity_mask & (df['pred_load_label'] == 'Medium')]

    print(f"\n🔍 Low Activity Analysis:")
    print(f"  Criteria: PRB<{LOW_THRESHOLDS['RRU.PrbTotDl']}, "
          f"Tput<{LOW_THRESHOLDS['DRB.UEThpDl']}, "
          f"Vol<{LOW_THRESHOLDS['DRB.PdcpSduVolumeDL']}")
    print(f"\n  Total low activity rows:  {low_activity_mask.sum()} ({low_activity_mask.sum()/len(df):.1%})")
    print(f"  ⚠️  Predicted as Heavy:    {len(suspicious_heavy)} ({len(suspicious_heavy)/len(df):.1%})")
    print(f"  ⚠️  Predicted as Medium:   {len(suspicious_medium)} ({len(suspicious_medium)/len(df):.1%})")
    print(f"  ✓  Predicted as Light:    {low_activity_mask.sum() - len(suspicious_heavy) - len(suspicious_medium)}")

    if len(suspicious_heavy) > 0 or len(suspicious_medium) > 0:
        print(f"\n  💡 Insight: {len(suspicious_heavy) + len(suspicious_medium)} potentially incorrect predictions")
        print(f"     These rows have very low features but are predicted as Heavy/Medium.")

    # Expected load distribution by slice type
    expected_distribution = {
        'eMBB': {'Light': (0, 20), 'Medium': (30, 50), 'Heavy': (40, 70)},
        'mMTC': {'Light': (40, 70), 'Medium': (20, 40), 'Heavy': (0, 20)},
        'URLLC': {'Light': (30, 60), 'Medium': (20, 40), 'Heavy': (10, 30)}
    }

    print(f"\n🎯 Expected Distribution for {slice_type}:")
    actual_dist = df['pred_load_label'].value_counts(normalize=True) * 100

    if slice_type in expected_distribution:
        for label, (min_exp, max_exp) in expected_distribution[slice_type].items():
            actual = actual_dist.get(label, 0)
            status = "✓" if min_exp <= actual <= max_exp else "⚠️"
            print(f"  {status} {label:<8}: Expected {min_exp}-{max_exp}%, Actual {actual:.1f}%")


def print_anomalies(df: pd.DataFrame):
    """Detect and report anomalies"""
    print(f"\n{'─'*90}")
    print("5. ANOMALY DETECTION")
    print(f"{'─'*90}")

    anomalies = []

    # Anomaly 1: Zero throughput but Heavy load
    zero_tput_heavy = df[(df['DRB.UEThpDl'] == 0) & (df['pred_load_label'] == 'Heavy')]
    if len(zero_tput_heavy) > 0:
        anomalies.append(f"⚠️  {len(zero_tput_heavy)} rows: Zero throughput but predicted Heavy")

    # Anomaly 2: Very high PRB but Light load
    high_prb_light = df[(df['RRU.PrbTotDl'] > 80) & (df['pred_load_label'] == 'Light')]
    if len(high_prb_light) > 0:
        anomalies.append(f"⚠️  {len(high_prb_light)} rows: High PRB (>80%) but predicted Light")

    # Anomaly 3: High throughput but low allocation
    high_tput_low_alloc = df[(df['DRB.UEThpDl'] > 100) & (df['pred_action'] == 0)]
    if len(high_tput_low_alloc) > 0:
        anomalies.append(f"⚠️  {len(high_tput_low_alloc)} rows: High throughput (>100 Mbps) but low allocation (20%)")

    # Anomaly 4: Very high delay but Light load
    high_delay_light = df[(df['DRB.RlcSduDelayDl'] > 500) & (df['pred_load_label'] == 'Light')]
    if len(high_delay_light) > 0:
        anomalies.append(f"⚠️  {len(high_delay_light)} rows: High delay (>500ms) but predicted Light")

    # Anomaly 5: Constant predictions (model might be stuck)
    if df['pred_load_label'].nunique() == 1:
        anomalies.append(f"⚠️  All predictions are '{df['pred_load_label'].iloc[0]}' - model may need retraining")

    if anomalies:
        print(f"\n🚨 Detected Anomalies:")
        for i, anomaly in enumerate(anomalies, 1):
            print(f"  {i}. {anomaly}")
    else:
        print(f"\n✓ No significant anomalies detected")


def print_action_load_consistency(df: pd.DataFrame):
    """Check consistency between load predictions and action decisions"""
    print(f"\n{'─'*90}")
    print("6. ACTION-LOAD CONSISTENCY")
    print(f"{'─'*90}")

    print(f"\n📊 Action Distribution by Load Label:")
    print(f"{'Load':<10} {'Action 0 (20%)':>16} {'Action 1 (50%)':>16} {'Action 2 (80%)':>16}")
    print(f"{'-'*60}")

    for load in ['Light', 'Medium', 'Heavy']:
        load_data = df[df['pred_load_label'] == load]
        if len(load_data) > 0:
            action_counts = load_data['pred_action'].value_counts()
            a0 = action_counts.get(0, 0) / len(load_data) * 100
            a1 = action_counts.get(1, 0) / len(load_data) * 100
            a2 = action_counts.get(2, 0) / len(load_data) * 100
            print(f"{load:<10} {a0:>15.1f}% {a1:>15.1f}% {a2:>15.1f}%")

    # Check for inconsistencies
    print(f"\n💡 Consistency Insights:")

    # Heavy load should prefer high allocation
    heavy_data = df[df['pred_load_label'] == 'Heavy']
    if len(heavy_data) > 0:
        heavy_low_alloc = (heavy_data['pred_action'] == 0).sum()
        if heavy_low_alloc / len(heavy_data) > 0.5:
            print(f"  ⚠️  {heavy_low_alloc}/{len(heavy_data)} Heavy loads got low allocation (20%)")
        else:
            print(f"  ✓  Heavy loads appropriately allocated")

    # Light load should prefer low allocation
    light_data = df[df['pred_load_label'] == 'Light']
    if len(light_data) > 0:
        light_high_alloc = (light_data['pred_action'] == 2).sum()
        if light_high_alloc / len(light_data) > 0.3:
            print(f"  ⚠️  {light_high_alloc}/{len(light_data)} Light loads got high allocation (80%)")
        else:
            print(f"  ✓  Light loads appropriately allocated")


# =============================================================================
# BATCH REPORTING
# =============================================================================

def generate_all_reports(embb_results: Dict[int, pd.DataFrame],
                        mmtc_results: Dict[int, pd.DataFrame],
                        urllc_results: Dict[int, pd.DataFrame]):
    """
    Generate reports for all UEs across all slices

    Parameters
    ----------
    embb_results : dict
        {ue_id: results_df} for eMBB slice
    mmtc_results : dict
        {ue_id: results_df} for mMTC slice
    urllc_results : dict
        {ue_id: results_df} for URLLC slice
    """
    print("\n" + "="*90)
    print("GENERATING REPORTS FOR ALL UEs")
    print("="*90 + "\n")

    # eMBB reports
    for ue_id, results_df in embb_results.items():
        generate_inference_report(results_df, f'UE{ue_id}', 'eMBB')

    # mMTC reports
    for ue_id, results_df in mmtc_results.items():
        generate_inference_report(results_df, f'UE{ue_id}', 'mMTC')

    # URLLC reports
    for ue_id, results_df in urllc_results.items():
        generate_inference_report(results_df, f'UE{ue_id}', 'URLLC')


def generate_summary_report(embb_results: Dict[int, pd.DataFrame],
                           mmtc_results: Dict[int, pd.DataFrame],
                           urllc_results: Dict[int, pd.DataFrame]):
    """
    Generate high-level summary across all slices
    """
    print("\n" + "="*90)
    print("SUMMARY REPORT: ALL SLICES")
    print("="*90)

    slices = {
        'eMBB': embb_results,
        'mMTC': mmtc_results,
        'URLLC': urllc_results
    }

    print(f"\n{'Slice':<10} {'UEs':>6} {'Samples':>10} {'Light':>10} {'Medium':>10} {'Heavy':>10}")
    print(f"{'-'*58}")

    for slice_name, ue_results in slices.items():
        if not ue_results:
            continue

        # Combine all UEs for this slice
        all_data = pd.concat(ue_results.values(), ignore_index=True)

        num_ues = len(ue_results)
        num_samples = len(all_data)

        load_dist = all_data['pred_load_label'].value_counts(normalize=True) * 100
        light = load_dist.get('Light', 0)
        medium = load_dist.get('Medium', 0)
        heavy = load_dist.get('Heavy', 0)

        print(f"{slice_name:<10} {num_ues:>6} {num_samples:>10} {light:>9.1f}% {medium:>9.1f}% {heavy:>9.1f}%")

    print("="*90 + "\n")


# =============================================================================
# USAGE EXAMPLE
# =============================================================================

if __name__ == "__main__":
    # Example: Generate report for single UE
    # generate_inference_report(embb_ue3_results, 'UE3', 'eMBB')

    # Example: Generate reports for all UEs
    # embb_results = {3: embb_ue3_results, 4: embb_ue4_results, 5: embb_ue5_results}
    # mmtc_results = {1: mmtc_ue1_results, 2: mmtc_ue2_results, ...}
    # urllc_results = {1: urllc_ue1_results, 2: urllc_ue2_results, ...}
    #
    # generate_all_reports(embb_results, mmtc_results, urllc_results)
    # generate_summary_report(embb_results, mmtc_results, urllc_results)

    print("Inference report generator ready!")

# Single UE report
# generate_inference_report(embb_ue3_results, 'UE3', 'eMBB')


embb_results = {
    3: embb_ue3_results,
    4: embb_ue4_results,
    5: embb_ue5_results
}

mmtc_results = {
    1: mmtc_ue1_results,
    2: mmtc_ue2_results,
    3: mmtc_ue3_results,
    4: mmtc_ue4_results,
    5: mmtc_ue5_results
}

urllc_results = {
    1: urllc_ue1_results,
    2: urllc_ue2_results,
    3: urllc_ue3_results,
    4: urllc_ue4_results,
    5: urllc_ue5_results
}

# All UEs in one slice
for ue_id, results in embb_results.items():
    generate_inference_report(results, f'UE{ue_id}', 'eMBB')

for ue_id, results in mmtc_results.items():
    generate_inference_report(results, f'UE{ue_id}', 'mMTC')

for ue_id, results in urllc_results.items():
    generate_inference_report(results, f'UE{ue_id}', 'URLLC')

# Summary across all slices
generate_summary_report(embb_results, mmtc_results, urllc_results)

"""## Take-away report"""

def generate_inference_report_compact(results_df: pd.DataFrame,
                                     ue_name: str,
                                     slice_type: str) -> None:
    """
    Generate compact inference report with validation, anomalies, and consistency only

    Parameters
    ----------
    results_df : pd.DataFrame
        DataFrame with inference results
    ue_name : str
        UE identifier (e.g., 'UE3')
    slice_type : str
        Slice type: 'eMBB', 'mMTC', or 'URLLC'
    """
    print("="*90)
    print(f"INFERENCE REPORT: {slice_type} - {ue_name}")
    print("="*90)

    # 4. Prediction Validation
    print_prediction_validation(results_df, slice_type)

    # 5. Anomaly Detection
    print_anomalies(results_df)

    # 6. Action-Load Consistency
    print_action_load_consistency(results_df)

    print("="*90 + "\n")


# Keep the same helper functions for sections 4, 5, 6
def print_prediction_validation(df: pd.DataFrame, slice_type: str):
    """Validate predictions against expected behavior"""
    print(f"\n{'─'*90}")
    print("PREDICTION VALIDATION")
    print(f"{'─'*90}")

    # Define thresholds for "low activity" features
    LOW_THRESHOLDS = {
        'RRU.PrbTotDl': 20,
        'DRB.UEThpDl': 10,
        'DRB.RlcSduDelayDl': 50,
        'DRB.PdcpSduVolumeDL': 100,
        'DRB.PdcpSduVolumeUL': 100
    }

    # Find rows with low activity but predicted as Heavy/Medium
    low_activity_mask = (
        (df['RRU.PrbTotDl'] < LOW_THRESHOLDS['RRU.PrbTotDl']) &
        (df['DRB.UEThpDl'] < LOW_THRESHOLDS['DRB.UEThpDl']) &
        (df['DRB.PdcpSduVolumeDL'] < LOW_THRESHOLDS['DRB.PdcpSduVolumeDL']) &
        (df['DRB.PdcpSduVolumeUL'] < LOW_THRESHOLDS['DRB.PdcpSduVolumeUL'])
    )

    suspicious_heavy = df[low_activity_mask & (df['pred_load_label'] == 'Heavy')]
    suspicious_medium = df[low_activity_mask & (df['pred_load_label'] == 'Medium')]

    print(f"\n🔍 Low Activity Analysis (PRB<20, Tput<10, Vol<100):")
    print(f"  Total low activity:  {low_activity_mask.sum():4d} ({low_activity_mask.sum()/len(df):5.1%})")
    print(f"  ⚠️  Predicted Heavy:  {len(suspicious_heavy):4d} ({len(suspicious_heavy)/len(df):5.1%})")
    print(f"  ⚠️  Predicted Medium: {len(suspicious_medium):4d} ({len(suspicious_medium)/len(df):5.1%})")
    print(f"  ✓  Predicted Light:  {low_activity_mask.sum() - len(suspicious_heavy) - len(suspicious_medium):4d}")

    if len(suspicious_heavy) > 0 or len(suspicious_medium) > 0:
        print(f"\n  💡 {len(suspicious_heavy) + len(suspicious_medium)} potentially incorrect predictions")

    # Expected distribution by slice
    expected_distribution = {
        'eMBB': {'Light': (0, 20), 'Medium': (30, 50), 'Heavy': (40, 70)},
        'mMTC': {'Light': (40, 70), 'Medium': (20, 40), 'Heavy': (0, 20)},
        'URLLC': {'Light': (30, 60), 'Medium': (20, 40), 'Heavy': (10, 30)}
    }

    print(f"\n🎯 Expected vs Actual Distribution:")
    actual_dist = df['pred_load_label'].value_counts(normalize=True) * 100

    if slice_type in expected_distribution:
        for label, (min_exp, max_exp) in expected_distribution[slice_type].items():
            actual = actual_dist.get(label, 0)
            status = "✓" if min_exp <= actual <= max_exp else "⚠️"
            print(f"  {status} {label:<8}: Expected {min_exp:2d}-{max_exp:2d}%, Actual {actual:5.1f}%")


def print_anomalies(df: pd.DataFrame):
    """Detect and report anomalies"""
    print(f"\n{'─'*90}")
    print("ANOMALY DETECTION")
    print(f"{'─'*90}")

    anomalies = []

    # Anomaly 1: Zero throughput but Heavy load
    zero_tput_heavy = df[(df['DRB.UEThpDl'] == 0) & (df['pred_load_label'] == 'Heavy')]
    if len(zero_tput_heavy) > 0:
        anomalies.append(f"{len(zero_tput_heavy):4d} rows: Zero throughput → Heavy")

    # Anomaly 2: Very high PRB but Light load
    high_prb_light = df[(df['RRU.PrbTotDl'] > 80) & (df['pred_load_label'] == 'Light')]
    if len(high_prb_light) > 0:
        anomalies.append(f"{len(high_prb_light):4d} rows: High PRB (>80%) → Light")

    # Anomaly 3: High throughput but low allocation
    high_tput_low_alloc = df[(df['DRB.UEThpDl'] > 100) & (df['pred_action'] == 0)]
    if len(high_tput_low_alloc) > 0:
        anomalies.append(f"{len(high_tput_low_alloc):4d} rows: High throughput (>100 Mbps) → Low allocation (20%)")

    # Anomaly 4: Very high delay but Light load
    high_delay_light = df[(df['DRB.RlcSduDelayDl'] > 500) & (df['pred_load_label'] == 'Light')]
    if len(high_delay_light) > 0:
        anomalies.append(f"{len(high_delay_light):4d} rows: High delay (>500ms) → Light")

    # Anomaly 5: Constant predictions
    if df['pred_load_label'].nunique() == 1:
        anomalies.append(f"All predictions are '{df['pred_load_label'].iloc[0]}' (model stuck?)")

    if anomalies:
        print(f"\n🚨 Detected Anomalies:")
        for i, anomaly in enumerate(anomalies, 1):
            print(f"  {i}. ⚠️  {anomaly}")
    else:
        print(f"\n✓ No significant anomalies detected")


def print_action_load_consistency(df: pd.DataFrame):
    """Check consistency between load and action"""
    print(f"\n{'─'*90}")
    print("ACTION-LOAD CONSISTENCY")
    print(f"{'─'*90}")

    print(f"\n📊 Action Distribution by Load:")
    print(f"{'Load':<10} {'Action 0 (20%)':>16} {'Action 1 (50%)':>16} {'Action 2 (80%)':>16}")
    print(f"{'-'*60}")

    for load in ['Light', 'Medium', 'Heavy']:
        load_data = df[df['pred_load_label'] == load]
        if len(load_data) > 0:
            action_counts = load_data['pred_action'].value_counts()
            a0 = action_counts.get(0, 0) / len(load_data) * 100
            a1 = action_counts.get(1, 0) / len(load_data) * 100
            a2 = action_counts.get(2, 0) / len(load_data) * 100
            print(f"{load:<10} {a0:>15.1f}% {a1:>15.1f}% {a2:>15.1f}%")

    # Consistency checks
    print(f"\n💡 Insights:")

    # Heavy → should get high allocation
    heavy_data = df[df['pred_load_label'] == 'Heavy']
    if len(heavy_data) > 0:
        heavy_low_alloc = (heavy_data['pred_action'] == 0).sum()
        if heavy_low_alloc / len(heavy_data) > 0.5:
            print(f"  ⚠️  {heavy_low_alloc}/{len(heavy_data)} Heavy loads got low allocation")
        else:
            print(f"  ✓  Heavy loads appropriately allocated")

    # Light → should get low allocation
    light_data = df[df['pred_load_label'] == 'Light']
    if len(light_data) > 0:
        light_high_alloc = (light_data['pred_action'] == 2).sum()
        if light_high_alloc / len(light_data) > 0.3:
            print(f"  ⚠️  {light_high_alloc}/{len(light_data)} Light loads got high allocation")
        else:
            print(f"  ✓  Light loads appropriately allocated")


# Usage
def generate_all_compact_reports(embb_results, mmtc_results, urllc_results):
    """Generate compact reports for all UEs"""

    # eMBB
    for ue_id, results_df in embb_results.items():
        generate_inference_report_compact(results_df, f'UE{ue_id}', 'eMBB')

    # mMTC
    for ue_id, results_df in mmtc_results.items():
        generate_inference_report_compact(results_df, f'UE{ue_id}', 'mMTC')

    # URLLC
    for ue_id, results_df in urllc_results.items():
        generate_inference_report_compact(results_df, f'UE{ue_id}', 'URLLC')

generate_all_compact_reports(embb_results, mmtc_results, urllc_results)

embb_results = {
    0: embb_test_results
}
mmtc_results = {
    0: mmtc_test_results
}
urllc_results = {
    0: urllc_test_results
}
generate_all_compact_reports(embb_results, mmtc_results, urllc_results)