tractor-kpm-oai:
  enabled: true
  fullnameOverride: "tractor-kpm-oai"
  nodeSelector:
    node-role: core
  image:
    tag: kcl
  env:
    ORCH_HOST: xchain-kcl
    ORCH_PORT: "4500"
    NUM_UES: "3"

tractor-kpm-simu:
  enabled: false
  fullnameOverride: "tractor-kpm-simu"
  nodeSelector:
    node-role: core
  image:
    tag: latest
  env:
    ORCH_HOST: tractor-mono

tractor-orchestrator:
  enabled: false
  fullnameOverride: "tractor-orchestrator"
  nodeSelector:
    node-role: core
  image:
    tag: latest
  env:
    T: "32"

tractor-normalizer:
  enabled: false
  fullnameOverride: "tractor-normalizer"
  nodeSelector:
    node-role: core
  image:
    tag: latest
  persistentVolume:
    hostPath: /home/lapdk/workspace/oai-v210/xChain/src/xapp/models
  env:
    T: "32"

tractor-buffer:
  enabled: false
  fullnameOverride: "tractor-buffer"
  nodeSelector:
    node-role: core
  image:
    tag: latest

tractor-model:
  enabled: false
  fullnameOverride: "tractor-model"
  nodeSelector:
    node-role: core
  image:
    tag: latest
  persistentVolume:
    hostPath: /home/lapdk/workspace/oai-v210/xChain/src/xapp/models
  volumeMounts:
    model:
      subPath: model.32.cnn.pt

tractor-mono:
  enabled: false
  fullnameOverride: "tractor-mono"
  nodeSelector:
    node-role: core
  image:
    tag: latest
  persistentVolume:
    model:
      hostPath: /home/lapdk/workspace/oai-v210/xChain/src/xapp/models
    norm:
      hostPath: /home/lapdk/workspace/oai-v210/xChain/src/xapp/models
  env:
    T: "4"
  volumeMounts:
    model:
      subPath: model.4.cnn.pt

xchain-orchestrator:
  enabled: false
  fullnameOverride: "xchain-orchestrator"
  nodeSelector:
    node-role: core
  image:
    tag: latest
  env:
    TRACTOR_HOST:   tractor-orchestrator
    TRACTOR_PORT:   "4300"
    FASTINFER_HOST: xchain-fastinfer
    FASTINFER_PORT: "4400"

xchain-smartgw:
  enabled: false
  fullnameOverride: "xchain-smartgw"
  nodeSelector:
    node-role: core
  image:
    tag: latest
  persistentVolume:
    hostPath: /home/lapdk/workspace/oai-v210/xChain/src/smartGW
    subPath: smartgw_0134.pkl
  env:
    ORCH_HOST:          xchain-orchestrator
    ORCH_PORT:          "5010"
    ORCH_POLL_INTERVAL: "30"
    

xchain-kcl:
  enabled: true
  fullnameOverride: "xchain-kcl"
  nodeSelector:
    node-role: core
  image:
    tag: latest
  env:
    LISTEN_PORT: "4500"
    MODELS_DIR: /models
    LABELING_MODEL: labeling_xapp.pth
    RESOURCE_MODEL: resource_xapp.pth
    SCALER_FILE: scaler.pkl
    NUM_UES: "3"
    T: "4"
  persistentVolume:
    hostPath: /home/lapdk/workspace/oai-v210/xChain/src/kcl

xchain-fastinfer:
  enabled: false
  fullnameOverride: "xchain-fastinfer"
  nodeSelector:
    node-role: core
  image:
    tag: latest
  persistentVolume:
    hostPath: /home/lapdk/workspace/oai-v210/xChain/src/xapp-fastinfer
    subPath: xgb_model_T_4.json
  env:
    T: "4"