replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: ddocker122/tractor-xapp-normalizer
  tag: latest

service:
  port: 5002

serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ''

volumeMounts:
  norm:
    mountPath: /mnt/model/norm.pkl

persistentVolume:
  enabled: true
  name: tractor-normalizer-pv
  claimName: tractor-normalizer-pvc
  size: 1Gi
  accessMode: ReadWriteMany
  hostPath: /home/ubuntu/binh/oai-v210/tractor/src/xapp/models
  reclaimPolicy: Delete
  
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
