apiVersion: v1
kind: Service
metadata:
  name: {{ include "tractor-mono.fullname" . }}
  labels:
    {{- include "tractor-mono.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.kpm-port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tractor-mono.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tractor-mono.fullname" . }}
  labels:
    {{- include "tractor-mono.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.mono-port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tractor-mono.selectorLabels" . | nindent 4 }}