apiVersion: v1
kind: Service
metadata:
  name: oai-nearrt-ric
  labels:
    {{- include "oai-nearrt-ric.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: e2
      port: 36421
      targetPort: 36421
      protocol: SCTP
  selector:
    {{- include "oai-nearrt-ric.selectorLabels" . | nindent 4 }}
