apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo-deployment
  namespace: oai
  labels:
    app: http-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo
        args:
          - "-text=Hello from http-echo"
        ports:
          - containerPort: 5678
        imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo-service
  namespace: oai
spec:
  clusterIP: 10.96.10.30
  type: NodePort
  selector:
    app: http-echo
  ports:
  - port: 5678
    targetPort: 5678
    nodePort: 30996
