apiVersion: v1
kind: Pod
metadata:
  name: ping-pod
  namespace: oai
  labels:
    app: ping-server
spec:
  containers:
  - name: ping-container
    image: busybox
    command: ["sleep", "3600"]  # Keep the pod running
