{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oai-xapp-gtp-mac-rlc-pdcp-moni.serviceAccountName" . }}
  labels:
    {{- include "oai-xapp-gtp-mac-rlc-pdcp-moni.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
