apiVersion: v1
kind: Service
metadata:
  name: {{ include "tractor-mono.fullname" . }}
  labels:
    {{- include "tractor-mono.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType | default "ClusterIP" }}
  ports:
    {{- range .Values.service }}
    - name: {{ .name }}
      port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      protocol: TCP
    {{- end }}
    {{- if .Values.agent.enabled }}
    - name: agent-http
      port: {{ .Values.agent.env.AGENT_PORT | default "5100" }}
      targetPort: {{ .Values.agent.env.AGENT_PORT | default "5100" }}
      protocol: TCP
    - name: agent-data
      port: {{ .Values.agent.env.AGENT_DATA_PORT | default "4301" }}
      targetPort: {{ .Values.agent.env.AGENT_DATA_PORT | default "4301" }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "tractor-mono.selectorLabels" . | nindent 4 }}
