apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tractor-model.fullname" . }}
  labels:
    {{- include "tractor-model.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tractor-model.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tractor-model.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      containers:
        - name: tractor-model
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: model
              mountPath: {{ .Values.volumeMounts.model.mountPath }}
              subPath: model.32.cnn.pt
          resources:
{{ toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: model
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolume.claimName }}
