replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: ddocker122/tractor-xapp-buffer
  tag: latest

service:
  port: 5005

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}