replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: ddocker122/tractor-kpm-sim
  tag: latest

env:
  ORCH_HOST: tractor-orchestrator
  ORCH_PORT: '4200'

service:
  port: 4200
  type: ClusterIP

serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ''

volumeMounts:
  kpisCsv:
    hostPath: 
      /home/lapdk/workspace/oai-v210/tractor/src/kpm-sim/embb1010123456002_metrics.csv
    mountPath: /app/kpis.csv
resources: {}
nodeSelector: []
tolerations: []
affinity: {}
