apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  flexric.conf: |
    [NEAR-RIC]
    NEAR_RIC_IP = {{ .Values.config.nearRtHost }}
    
    [XAPP]
    DB_DIR = /tmp/
    ATD_SERVER_IP = {{ .Values.multus.a1Interface.ipAdd }}
    GNB_TELNET_IP = {{ .Values.config.gnbTelnetIp }}
