apiVersion: v1
kind: Service
metadata:
  name: {{ include "xchain-gui-server.fullname" . }}
  labels:
    {{- include "xchain-gui-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType | default "ClusterIP" }}
  ports:
    {{- range .Values.service }}
    - name: {{ .name }}
      port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      protocol: TCP
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "xchain-gui-server.selectorLabels" . | nindent 4 }}
