apiVersion: v1
kind: Service
metadata:
  name: oai-xapp-kpm-moni
  labels:
    {{- include "oai-xapp-kpm-moni.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: e2
      port: 36422
      targetPort: 36422
      protocol: SCTP
  selector:
    {{- include "oai-xapp-kpm-moni.selectorLabels" . | nindent 4 }}
