replicaCount: 1

image:
  repository: ddocker122/xchain-gui-server
  tag: latest
  pullPolicy: IfNotPresent

fullnameOverride: "xchain-gui-server"

serviceAccount:
  create: true
  name: "xchain-gui-server-sa"
  automount: true
  annotations: {}

serviceType: NodePort

service:
  - name: http
    containerPort: 5000
    nodePort: 30500
  - name: agent-tcp
    containerPort: 4000
    nodePort: 30400

env:
  BASE_DIR:                   /results/
  REFRESH_INTERVAL:           "2"
  SOCKET_PORT:                "4000"
  TRAFFIC_SERVER_HOSTNAME:    oai-traffic-server
  TRAFFIC_SERVER_CMD_VR:      "start:bash -c 'cd /traffic-gen && ./replay_pcap.sh pcap/demo/vr.pcap'"
  TRAFFIC_SERVER_CMD_HAPTIC:  "start:bash -c 'cd /traffic-gen && ./replay_pcap.sh pcap/demo/haptic.pcap'"
  TRAFFIC_SERVER_CMD_SOCIAL:  "start:bash -c 'cd /traffic-gen && ./replay_pcap.sh pcap/demo/social.pcap'"
  TRAFFIC_SERVER_CMD_IOT:     "start:bash -c 'cd /traffic-gen && ./replay_pcap.sh pcap/demo/iot.pcap'"
  SMARTGW_HOSTNAME:           xchain-smartgw-demo
  SMARTGW_CMD_MODELS:         "start:{models}"
  MODELS_CONFIG:              '[{"value":"fastinferv1","label":"FastInfer-v1","foregroundColor":"#dd2d4a","backgroundColor":"","icon":"/assets/images/icons/fastinf.png","css_class":"fastinfer-card","isSelected":false},{"value":"cnnv1","label":"CNN-v1","foregroundColor":"#33658a","backgroundColor":"","icon":"/assets/images/icons/cnn.png","css_class":"cnn-card","isSelected":false},{"value":"fastinferv2","label":"FastInfer-v2","foregroundColor":"#9b1f34","backgroundColor":"","icon":"/assets/images/icons/fastinf.png","css_class":"fastinfer-card","isSelected":true},{"value":"cnnv2","label":"CNN-v2","foregroundColor":"#244761","backgroundColor":"","icon":"/assets/images/icons/cnn.png","css_class":"cnn-card","isSelected":true}]'


# Shared results PVC
# type: nfs (distributed) or hostPath (single-node)
persistentVolume:
  enabled: true
  name: demo-results-pv
  claimName: demo-results-pvc
  size: 5Gi
  accessMode: ReadWriteMany
  reclaimPolicy: Delete
  mountPath: /results
  type: nfs
  nfs:
    server: 192.168.21.153
    path: /home/core/oai-v210/xChain/src/2026-netsoft-demo/api/server/demo/data
  hostPath: /home/core/oai-v210/xChain/src/2026-netsoft-demo/api/server/demo/data

resources: {}
nodeSelector:
  node-role: core
affinity: {}
tolerations: []
